FROM node:lts-alpine3.19 AS build

WORKDIR /usr/src/app

COPY package*.json ./

RUN --mount=type=cache,target=/usr/src/app/.npm \
    npm set cache /usr/src/app/.npm && \
    npm ci --omit=optional --verbose

COPY . .


RUN npm run build

FROM nginxinc/nginx-unprivileged:1.26-bookworm-perl

COPY --link nginx.conf /etc/nginx/conf.d/default.conf

COPY --link --from=build /usr/src/app/build/ /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
